Timetable parser for #2
profcomff/data-pipelines pull request #3
Opened 2021-12-07 18:48 UTC by Daiwery

2021-12-07 19:07 UTC, dyakovri requested changes
В целом круто, посмотри на замечания

Оно точно отрабатывает на всех курсах? Мне кажется, тут не все варианты пар есть. Например мигающая пара, где половинка разная для разных подгрупп (http://ras.phys.msu.ru/table/4/1/6.htm среда, вторая пара) работает?

2021-12-09 07:47 UTC, Daiwery commented
В  http://ras.phys.msu.ru/table/4/1/6.htm среда, вторая пара - и правда была ошибка. Я слегка изменил алгоритм, теперь он должен все нормально делать.

2021-12-28 17:14 UTC, dyakovri commented
Если честно, то читать код стало тяжелее. Похоже, что я не оч сформулировал что хотел. 

Смотри, я немного преобразовал твой код, получилось так:

```python
from typing import List, Dict
from bs4 import BeautifulSoup as BS

class Group:
    def __init__(self, html: BS):
        self.data = html
        self.tags = []
        self.result = []
    
    def run(self) -> List[Dict[str, str]]:
        body = self.data.select("body")[0]
        rows = body.select("tr")[1]
        self.tags = list(filter(lambda x: x != "\n", rows.children))

        group = self.get_group()
        lessons = self.get_lessons()
        for lesson in lessons:
            self.result.append(dict(**lesson, group=group))
        return self.result
        
    def get_group(self) -> str:
        """Номер группы из заголовка страницы."""
        return self.tags[1].text
    
    def get_lessons(self) -> List[Dict[str, str]]:
        """Список предметов."""
        lessons = []
        weekday = 0
        lesson_num = 1
        
        for tag in self.tags[2:-1]:
            if len(tag.select("td.delimiter")) != 0:
                # Парсим разрывы дней
                lesson_num = 1
                weekday += 1
                continue
            lesson = Lesson(tag).run()
            lesson['weekday'] = weekday
            lesson['num'] = lesson_num
            lesson['start'] = lesson.get('start') or lessons[-1]['start']
            lesson['end'] = lesson.get('end') or lessons[-1]['end']
            if lesson['type'] in ['KIND_ITEM1', 'KIND_SMALL1_WITHOUT_TIME', 'KIND_SMALL1_WITH_SMALL0_WITH_TIME']:
                lesson_num += 1
            lessons.append(lesson)
        return lessons


class Lesson:
    def __init__(self, html: BS):
        self.html = html
        self.type  = self.define_type()
        self.result = {}
    
    def run(self) -> List[Dict[str, str]]:
        if self.type == 'KIND_ITEM1':
            self.result = self.get_item1()
        elif self.type == 'KIND_SMALL1_WITH_TIME':
            self.result = self.get_small1_with_time()
        elif self.type == 'KIND_SMALL1_WITHOUT_TIME':
            self.result = self.get_small1_without_time()
        elif self.type == 'KIND_ITEM1_WITH_SMALL0':
            self.result = self.get_item1_with_small0()
        elif self.type == 'KIND_SMALL1_WITH_SMALL0_WITH_TIME':
            self.result = self.get_small1_with_small0_with_time()
        elif self.type == 'KIND_SMALL1_WITH_SMALL0_WITHOUT_TIME':
            self.result = self.get_small1_with_small0_without_time()
        else:
            raise RuntimeError('Unexpected type of lesson')
        self.result.update({'type': self.type})
        return self.result
    
    def define_type(self):
        if len(self.html.select("td.tditem1")) != 0:
            if len(self.html.select("td.tdsmall0")) != 0:
                return 'KIND_ITEM1_WITH_SMALL0'
            return 'KIND_ITEM1'

        if len(self.html.select("td.tdsmall1")) != 0:
            if len(self.html.select("td.tdsmall0")) != 0:
                if len(self.html.select("td.tdtime")) != 0:
                    return 'KIND_SMALL1_WITH_SMALL0_WITH_TIME'
                else:
                    return 'KIND_SMALL1_WITH_SMALL0_WITHOUT_TIME'
            else:
                if len(self.html.select("td.tdtime")) != 0:
                    return 'KIND_SMALL1_WITH_TIME'
                else:
                    return 'KIND_SMALL1_WITHOUT_TIME'
    
    def get_item1(self):
        html = self.html.select("td.tditem1")[0]
        time = self.html.select("td.tdtime")[0].contents
        return {"name": html.prettify(), "start": time[0], "end": time[-1], "odd": True, "even": True}


    def get_small1_with_time(self):
        html = self.html.select("td.tdsmall1")[0]
        time = self.html.select("td.tdtime")[0].contents
        return {"name": html.prettify(), "start": time[0], "end": time[-1], "odd": True, "even": False}


    def get_small1_without_time(self):
        html = self.html.select("td.tdsmall1")[0]
        return {"name": html.prettify(), "up": False, "bottom": True}


    def get_item1_with_small0(self):
        html = self.html.select("td.tdsmall0")[0]
        time = self.html.select("td.tdtime")[0].contents
        return {"name": html.prettify(), "start": time[0], "end": time[-1], "odd": True, "even": True}


    def get_small1_with_small0_with_time(self):
        html = self.html.select("td.tdsmall0")[0]
        time = self.html.select("td.tdtime")[0].contents
        return {"name": html.prettify(), "start": time[0], "end": time[-1], "odd": True, "even": False}


    def get_small1_with_small0_without_time(self):
        html = self.html.select("td.tdsmall0")[0]
        time = self.html.select("td.tdtime")[0].contents
        return {"name": html.prettify(), "start": time[0], "end": time[-1], "odd": False, "even": True}


def run(html: str) -> List[Dict[str, str]]:
    html = BS(html, "html.parser")
    tt = Group(html).run()
    return tt


# Эти штуки будут вне скрипта, мы их будем вызывать в Airflow
in __name__ == '__main__':
    import requests
    import pandas as pd
    USER_AGENT = "Mozilla/5.0 (Linux; Android 7.0; SM-G930V Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Mobile Safari/537.36"
    HEADERS = {"User-Agent": USER_AGENT}
    html = requests.get('http://ras.phys.msu.ru/table/1/1/1.htm', headers=HEADERS).content
    pd.DataFrame(run(html))```

2021-12-29 10:36 UTC, dyakovri approved these changes

2021-12-29 10:37 UTC, merged