Odd and even.
profcomff/data-pipelines pull request #4
Opened 2022-02-02 19:48 UTC by Daiwery

2022-02-08 12:40 UTC, dyakovri requested changes
Папку .idea стоит удалить. Это настройки твоего пользователя, их не надо шэрить всем пользователями. Чтобы она не попадала больше в коммиты сделай так https://stackoverflow.com/a/7335487

2022-02-08 12:40 UTC, dyakovri commented on timetable/timetable_parser.py
> -        return {"name": html.prettify(), "start": time[0], "end": time[-1], "odd": False, "even": True}
А времени тут нет?

2022-02-08 12:40 UTC, dyakovri commented on timetable/timetable_parser.py
> +    html = requests.get('http://ras.phys.msu.ru/table/{one}/{two}/{i}.htm', headers=HEADERS).content
А эти one, two, i откуда задаются? Мне кажется для теста можно и 1/1/1 оставить)

2022-02-08 15:43 UTC, Daiwery commented
Я, кажется, сделал коммит не в Pycharm, а отдельно. Странно, что .idea закомитилась.

2022-02-16 09:35 UTC, dyakovri approved these changes

2022-02-16 09:35 UTC, merged